type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      parameters:
        componentName: "Start"
    S3 Load:
      type: "s3-load"
      parameters:
        componentName: "S3 Load"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://matillion-projects-awa/"
        pattern: "awstest.csv"
        encryption: "None"
        warehouse: "COMPUTE_WH"
        database: "MATILLION"
        schema: "PUBLIC"
        targetTable: "s3_raw_data"
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter: |2+

        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "False"
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        onError: "Continue"
        purgeFiles: "False"
        matchByColumnName: "None"
        truncateColumns: "False"
        forceLoad: "False"
design:
  components:
    Start:
      position:
        x: -250
        "y": -60
      tempMetlId: 1
    S3 Load:
      position:
        x: -40
        "y": -60
      tempMetlId: 2
