type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Create Table"
      parameters:
        componentName: "Start"
    Create Table:
      type: "create-table-v2"
      transitions:
        success:
        - "S3 Load"
      parameters:
        componentName: "Create Table"
        createMethod: "Replace"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        table: "DEMOGRAPHIC"
        snowflakeTableType: "Permanent"
        columns:
        - - "CustomerID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "Yes"
          - "Yes"
          - ""
          - ""
        - - "LastName"
          - "VARCHAR"
          - "60"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "FirstName"
          - "VARCHAR"
          - "60"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "BirthDate"
          - "VARCHAR"
          - "20"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "Gender"
          - "VARCHAR"
          - "20"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "ParticipantType"
          - "VARCHAR"
          - "20"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "RegionID"
          - "NUMBER"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "MaritalStatus"
          - "VARCHAR"
          - "15"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        defaultDdlCollation:
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays:
        comment:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    S3 Load:
      type: "s3-load"
      parameters:
        componentName: "S3 Load"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://matillion-projects-awa/customer"
        pattern: ".*\\.csv$"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "DEMOGRAPHIC"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter:
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed:
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: -270
        "y": -110
      tempMetlId: 1
    Create Table:
      position:
        x: -110
        "y": -110
      tempMetlId: 2
    S3 Load:
      position:
        x: 40
        "y": -110
      tempMetlId: 3
